apiVersion: v1
kind: Secret
metadata:
  name: {{ template "backend.fullname" . }}-secret
type: Opaque
data:
  db-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  db-user: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  db-name: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
