name: change tag in helm charts
on:
  workflow_dispatch:
    inputs:
        new_tag:
          description: the tag to set in the helm chart
          required: true

        tier:
          description: specify the helm chart to modify
          required: true

env:
  TIER: ${{ github.event.inputs.tier }}
  TAG: ${{ github.event.inputs.new_tag }}
  
jobs:

  update-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: update tag in backend helm chart
        if: ${{ env.TIER == 'backend'}}
        run: |
          sed -i "s/ *tag:.*/tag: "${{ env.TAG }}"/" helm/backend/values.yaml 
          
      - name: update tag in frontend helm chart
        if: ${{ env.TIER == 'frontend'}}
        run: |
          sed -i "s/ *tag:.*/tag: "${{ env.TAG }}"/" helm/frontend/values.yaml 
          
      - name: Push to repo
        run: |
          git config --local user.email "github-actions@noreply.github.com"
          git config --local user.name "github-actions"
          git commit -m "Updated helm tag" -a
          git push
        
